


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ng_words" (
    "id" integer NOT NULL,
    "word" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."ng_words" OWNER TO "postgres";


ALTER TABLE "public"."ng_words" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ng_words_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."scores" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "score" bigint NOT NULL,
    "difficulty" "text" NOT NULL,
    "correct" integer DEFAULT 0,
    "miss" integer DEFAULT 0,
    "backspace" integer DEFAULT 0,
    "combo" integer DEFAULT 0,
    "speed" double precision DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "is_creator" boolean DEFAULT false,
    CONSTRAINT "anti_bot_check" CHECK ((("speed" <= (15)::double precision) OR ("miss" > 0))),
    CONSTRAINT "difficulty_check" CHECK (("difficulty" = ANY (ARRAY['EASY'::"text", 'NORMAL'::"text", 'HARD'::"text"]))),
    CONSTRAINT "name_length_check" CHECK (("char_length"("name") <= 10)),
    CONSTRAINT "score_ceiling_check" CHECK (("score" <= 99999999)),
    CONSTRAINT "scores_backspace_check" CHECK (("backspace" >= 0)),
    CONSTRAINT "scores_combo_check" CHECK (("combo" >= 0)),
    CONSTRAINT "scores_correct_check" CHECK (("correct" >= 0)),
    CONSTRAINT "scores_miss_check" CHECK (("miss" >= 0)),
    CONSTRAINT "scores_score_check" CHECK (("score" >= 0)),
    CONSTRAINT "scores_speed_check" CHECK (("speed" >= (0)::double precision))
);


ALTER TABLE "public"."scores" OWNER TO "postgres";


ALTER TABLE "public"."scores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."scores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."words" (
    "id" integer NOT NULL,
    "jp" character varying(255) NOT NULL,
    "roma" character varying(255) NOT NULL,
    "difficulty" character varying(10) NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE "public"."words" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."words_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."words_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."words_id_seq" OWNED BY "public"."words"."id";



ALTER TABLE ONLY "public"."words" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."words_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."ng_words"
    ADD CONSTRAINT "ng_words_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ng_words"
    ADD CONSTRAINT "ng_words_word_key" UNIQUE ("word");



ALTER TABLE ONLY "public"."scores"
    ADD CONSTRAINT "scores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."words"
    ADD CONSTRAINT "unique_jp" UNIQUE ("jp");



ALTER TABLE ONLY "public"."scores"
    ADD CONSTRAINT "unique_user_difficulty" UNIQUE ("user_id", "difficulty");



ALTER TABLE ONLY "public"."words"
    ADD CONSTRAINT "words_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_words_difficulty" ON "public"."words" USING "btree" ("difficulty");



CREATE POLICY "Allow public read access" ON "public"."ng_words" FOR SELECT USING (true);



CREATE POLICY "Allow public read access" ON "public"."words" FOR SELECT USING (true);



CREATE POLICY "Policy_Insert_Own" ON "public"."scores" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"())::"text" = ("user_id")::"text"));



CREATE POLICY "Policy_Select_Own" ON "public"."scores" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Policy_Update_Own" ON "public"."scores" FOR UPDATE TO "authenticated" USING ((("auth"."uid"())::"text" = ("user_id")::"text")) WITH CHECK ((("auth"."uid"())::"text" = ("user_id")::"text"));



ALTER TABLE "public"."ng_words" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."scores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."words" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."ng_words" TO "anon";
GRANT ALL ON TABLE "public"."ng_words" TO "authenticated";
GRANT ALL ON TABLE "public"."ng_words" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ng_words_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ng_words_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ng_words_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."scores" TO "anon";
GRANT ALL ON TABLE "public"."scores" TO "authenticated";
GRANT ALL ON TABLE "public"."scores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."scores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."words" TO "anon";
GRANT ALL ON TABLE "public"."words" TO "authenticated";
GRANT ALL ON TABLE "public"."words" TO "service_role";



GRANT ALL ON SEQUENCE "public"."words_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."words_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."words_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


